//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.main_infoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="main_info", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibrary.main_info")]
    [System.SerializableAttribute()]
    public partial class main_info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime created_onField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string decrypt_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid id_guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> pdpa_declareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> send_emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime created_on {
            get {
                return this.created_onField;
            }
            set {
                if ((this.created_onField.Equals(value) != true)) {
                    this.created_onField = value;
                    this.RaisePropertyChanged("created_on");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string decrypt_key {
            get {
                return this.decrypt_keyField;
            }
            set {
                if ((object.ReferenceEquals(this.decrypt_keyField, value) != true)) {
                    this.decrypt_keyField = value;
                    this.RaisePropertyChanged("decrypt_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid id_guid {
            get {
                return this.id_guidField;
            }
            set {
                if ((this.id_guidField.Equals(value) != true)) {
                    this.id_guidField = value;
                    this.RaisePropertyChanged("id_guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> pdpa_declare {
            get {
                return this.pdpa_declareField;
            }
            set {
                if ((this.pdpa_declareField.Equals(value) != true)) {
                    this.pdpa_declareField = value;
                    this.RaisePropertyChanged("pdpa_declare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> send_email {
            get {
                return this.send_emailField;
            }
            set {
                if ((this.send_emailField.Equals(value) != true)) {
                    this.send_emailField = value;
                    this.RaisePropertyChanged("send_email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="main_infoService.Imain_info")]
    public interface Imain_info {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/getMainUserInformationByEmail", ReplyAction="http://tempuri.org/Imain_info/getMainUserInformationByEmailResponse")]
        WebUI.main_infoService.main_info getMainUserInformationByEmail(string _emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/getMainUserInformationByEmail", ReplyAction="http://tempuri.org/Imain_info/getMainUserInformationByEmailResponse")]
        System.Threading.Tasks.Task<WebUI.main_infoService.main_info> getMainUserInformationByEmailAsync(string _emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/getMainUserInformationByEmailAndPassword", ReplyAction="http://tempuri.org/Imain_info/getMainUserInformationByEmailAndPasswordResponse")]
        WebUI.main_infoService.main_info getMainUserInformationByEmailAndPassword(string _emailAddress, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/getMainUserInformationByEmailAndPassword", ReplyAction="http://tempuri.org/Imain_info/getMainUserInformationByEmailAndPasswordResponse")]
        System.Threading.Tasks.Task<WebUI.main_infoService.main_info> getMainUserInformationByEmailAndPasswordAsync(string _emailAddress, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/setMainUserInformation", ReplyAction="http://tempuri.org/Imain_info/setMainUserInformationResponse")]
        string setMainUserInformation(string _firstName, string _lastName, string _emailAddress, int _pdpa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/setMainUserInformation", ReplyAction="http://tempuri.org/Imain_info/setMainUserInformationResponse")]
        System.Threading.Tasks.Task<string> setMainUserInformationAsync(string _firstName, string _lastName, string _emailAddress, int _pdpa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/updateMainUserInformation", ReplyAction="http://tempuri.org/Imain_info/updateMainUserInformationResponse")]
        string updateMainUserInformation(string _firstName, string _lastName, string _emailAddress, System.Guid _guid, string _password, int _pdpa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/updateMainUserInformation", ReplyAction="http://tempuri.org/Imain_info/updateMainUserInformationResponse")]
        System.Threading.Tasks.Task<string> updateMainUserInformationAsync(string _firstName, string _lastName, string _emailAddress, System.Guid _guid, string _password, int _pdpa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/removeMainUserInformation", ReplyAction="http://tempuri.org/Imain_info/removeMainUserInformationResponse")]
        string removeMainUserInformation(string _emailAddress, System.Guid _guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/removeMainUserInformation", ReplyAction="http://tempuri.org/Imain_info/removeMainUserInformationResponse")]
        System.Threading.Tasks.Task<string> removeMainUserInformationAsync(string _emailAddress, System.Guid _guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/updateEmailSendStatus", ReplyAction="http://tempuri.org/Imain_info/updateEmailSendStatusResponse")]
        string updateEmailSendStatus(bool _sendEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/updateEmailSendStatus", ReplyAction="http://tempuri.org/Imain_info/updateEmailSendStatusResponse")]
        System.Threading.Tasks.Task<string> updateEmailSendStatusAsync(bool _sendEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/updatePassword", ReplyAction="http://tempuri.org/Imain_info/updatePasswordResponse")]
        string updatePassword(string _password, System.Guid _guid, string _emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/updatePassword", ReplyAction="http://tempuri.org/Imain_info/updatePasswordResponse")]
        System.Threading.Tasks.Task<string> updatePasswordAsync(string _password, System.Guid _guid, string _emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/setTestData", ReplyAction="http://tempuri.org/Imain_info/setTestDataResponse")]
        string setTestData(string _testData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/setTestData", ReplyAction="http://tempuri.org/Imain_info/setTestDataResponse")]
        System.Threading.Tasks.Task<string> setTestDataAsync(string _testData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/getHello", ReplyAction="http://tempuri.org/Imain_info/getHelloResponse")]
        string getHello(string _para);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imain_info/getHello", ReplyAction="http://tempuri.org/Imain_info/getHelloResponse")]
        System.Threading.Tasks.Task<string> getHelloAsync(string _para);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Imain_infoChannel : WebUI.main_infoService.Imain_info, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Imain_infoClient : System.ServiceModel.ClientBase<WebUI.main_infoService.Imain_info>, WebUI.main_infoService.Imain_info {
        
        public Imain_infoClient() {
        }
        
        public Imain_infoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Imain_infoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Imain_infoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Imain_infoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebUI.main_infoService.main_info getMainUserInformationByEmail(string _emailAddress) {
            return base.Channel.getMainUserInformationByEmail(_emailAddress);
        }
        
        public System.Threading.Tasks.Task<WebUI.main_infoService.main_info> getMainUserInformationByEmailAsync(string _emailAddress) {
            return base.Channel.getMainUserInformationByEmailAsync(_emailAddress);
        }
        
        public WebUI.main_infoService.main_info getMainUserInformationByEmailAndPassword(string _emailAddress, string _password) {
            return base.Channel.getMainUserInformationByEmailAndPassword(_emailAddress, _password);
        }
        
        public System.Threading.Tasks.Task<WebUI.main_infoService.main_info> getMainUserInformationByEmailAndPasswordAsync(string _emailAddress, string _password) {
            return base.Channel.getMainUserInformationByEmailAndPasswordAsync(_emailAddress, _password);
        }
        
        public string setMainUserInformation(string _firstName, string _lastName, string _emailAddress, int _pdpa) {
            return base.Channel.setMainUserInformation(_firstName, _lastName, _emailAddress, _pdpa);
        }
        
        public System.Threading.Tasks.Task<string> setMainUserInformationAsync(string _firstName, string _lastName, string _emailAddress, int _pdpa) {
            return base.Channel.setMainUserInformationAsync(_firstName, _lastName, _emailAddress, _pdpa);
        }
        
        public string updateMainUserInformation(string _firstName, string _lastName, string _emailAddress, System.Guid _guid, string _password, int _pdpa) {
            return base.Channel.updateMainUserInformation(_firstName, _lastName, _emailAddress, _guid, _password, _pdpa);
        }
        
        public System.Threading.Tasks.Task<string> updateMainUserInformationAsync(string _firstName, string _lastName, string _emailAddress, System.Guid _guid, string _password, int _pdpa) {
            return base.Channel.updateMainUserInformationAsync(_firstName, _lastName, _emailAddress, _guid, _password, _pdpa);
        }
        
        public string removeMainUserInformation(string _emailAddress, System.Guid _guid) {
            return base.Channel.removeMainUserInformation(_emailAddress, _guid);
        }
        
        public System.Threading.Tasks.Task<string> removeMainUserInformationAsync(string _emailAddress, System.Guid _guid) {
            return base.Channel.removeMainUserInformationAsync(_emailAddress, _guid);
        }
        
        public string updateEmailSendStatus(bool _sendEmail) {
            return base.Channel.updateEmailSendStatus(_sendEmail);
        }
        
        public System.Threading.Tasks.Task<string> updateEmailSendStatusAsync(bool _sendEmail) {
            return base.Channel.updateEmailSendStatusAsync(_sendEmail);
        }
        
        public string updatePassword(string _password, System.Guid _guid, string _emailAddress) {
            return base.Channel.updatePassword(_password, _guid, _emailAddress);
        }
        
        public System.Threading.Tasks.Task<string> updatePasswordAsync(string _password, System.Guid _guid, string _emailAddress) {
            return base.Channel.updatePasswordAsync(_password, _guid, _emailAddress);
        }
        
        public string setTestData(string _testData) {
            return base.Channel.setTestData(_testData);
        }
        
        public System.Threading.Tasks.Task<string> setTestDataAsync(string _testData) {
            return base.Channel.setTestDataAsync(_testData);
        }
        
        public string getHello(string _para) {
            return base.Channel.getHello(_para);
        }
        
        public System.Threading.Tasks.Task<string> getHelloAsync(string _para) {
            return base.Channel.getHelloAsync(_para);
        }
    }
}
